# Generated by Django 4.0.2 on 2022-09-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('agencyname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scheam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('scheamname', models.CharField(max_length=100)),
                ('location', models.CharField(default='', max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('propertytype', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Appartment', 'Appartment'), ('Industrial', 'Industrial'), ('Office', 'Office')], default='', max_length=100)),
                ('size', models.CharField(max_length=500)),
                ('rooms', models.IntegerField()),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathroom', models.IntegerField(blank=True, default='')),
                ('builtyear', models.DateField()),
                ('propertystatus', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('is_feature', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builder')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/scheam')),
                ('scheam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.scheam')),
            ],
        ),
    ]
