# Generated by Django 4.0.2 on 2022-09-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('mobile', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Builder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buildername', models.CharField(max_length=100)),
                ('email', models.EmailField(default='', max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('agencyname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.IntegerField(null=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scheam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image')),
                ('scheamname', models.CharField(max_length=100)),
                ('location', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=1000)),
                ('state', models.CharField(default='', max_length=50)),
                ('zipcode', models.IntegerField()),
                ('price', models.FloatField(max_length=100)),
                ('propertytype', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial'), ('Appartment', 'Appartment'), ('Industrial', 'Industrial'), ('Office', 'Office')], default='', max_length=100)),
                ('size', models.IntegerField()),
                ('storeroom', models.IntegerField(blank=True, default='', null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathroom', models.IntegerField(blank=True, default='', null=True)),
                ('amenites', models.CharField(max_length=100)),
                ('builtyear', models.DateField()),
                ('propertystatus', models.CharField(default='', max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('is_feature', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builder')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimg', models.ImageField(blank=True, null=True, upload_to='image/profile')),
                ('address', models.CharField(default='', max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('buildername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builder')),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/scheam')),
                ('scheam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.scheam')),
            ],
        ),
    ]
