# Generated by Django 4.0.2 on 2022-10-13 11:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheam',
            name='ame',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Lift', 'LIFT'), ('Security', 'SECURITY'), ('Garden', 'GARDEN')], default=[], max_length=20, null=True),
        ),
    ]
