# Generated by Django 4.0.2 on 2022-09-07 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheam',
            name='rooms',
            field=models.IntegerField(default=''),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimg', models.ImageField(upload_to='image/profile')),
                ('address', models.CharField(default='', max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builder')),
            ],
        ),
    ]
