# Generated by Django 4.0.2 on 2022-09-07 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_scheam_rooms_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimg', models.ImageField(upload_to='image/profile')),
                ('address', models.CharField(default='', max_length=1000)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('mobile', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='profile_mobile', to='myapp.builder')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.builder')),
            ],
        ),
    ]
