# Generated by Django 4.0.2 on 2022-10-17 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_scheam_ame_alter_scheam_amenites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='builder',
            name='email',
        ),
    ]
