# Generated by Django 4.0.2 on 2022-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.ManyToManyField(related_name='profile_mobile', to='myapp.Builder'),
        ),
    ]
