# Generated by Django 4.0.2 on 2022-09-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='builder',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='builder',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builder',
            name='profileimg',
            field=models.ImageField(default=2, upload_to='image/profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='builder',
            name='zipcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
