# Generated by Django 4.0.2 on 2022-09-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_amenites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenites',
            name='AirConditioning',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='BasketballCourt',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='CleaningService',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='Dishwasher',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='Gym',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='HardwoodFlows',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='Lift',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='Microwave',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='OutdoorShower',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='PetFriendly',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='Refrigerator',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='ReservedParking',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='Security',
        ),
        migrations.RemoveField(
            model_name='amenites',
            name='SwimmingPool',
        ),
    ]
