# Generated by Django 4.0.2 on 2022-09-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_amenites_airconditioning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheam',
            name='amenites',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Amenites',
        ),
    ]
