# Generated by Django 4.0.2 on 2022-09-10 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_scheam_amenites_delete_amenites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheam',
            old_name='rooms',
            new_name='storeroom',
        ),
    ]
