# Generated by Django 4.0.2 on 2022-09-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_rename_rooms_scheam_storeroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheam',
            name='storeroom',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
