# Generated by Django 4.0.2 on 2022-09-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_scheam_storeroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheam',
            name='bathroom',
            field=models.IntegerField(blank=True, default='', null=True),
        ),
    ]
