# Generated by Django 4.0.2 on 2022-09-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_scheam_bathroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheam',
            name='amenites',
            field=models.TextField(),
        ),
    ]
