# Generated by Django 4.0.2 on 2022-09-13 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_scheam_amenites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheam',
            name='amenites',
        ),
    ]
