# Generated by Django 4.0.2 on 2022-09-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_scheam_amenites'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheam',
            name='amenites',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
