# Generated by Django 4.0.2 on 2022-09-13 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_scheam_amenites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheam',
            name='price',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheam',
            name='size',
            field=models.IntegerField(),
        ),
    ]
