# Generated by Django 4.0.2 on 2022-09-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_scheam_price_alter_scheam_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheam',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='scheam',
            name='zipcode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
