# Generated by Django 4.0.2 on 2022-09-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_scheam_address_scheam_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheam',
            name='state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
