# Generated by Django 4.0.2 on 2022-09-19 09:10

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_scheam_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='profileimg',
            field=imagekit.models.fields.ProcessedImageField(upload_to='image/profile'),
        ),
    ]
