# Generated by Django 4.0.2 on 2022-09-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_builder_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='profileimg',
            field=models.ImageField(upload_to='image/profile'),
        ),
    ]
