# Generated by Django 4.0.2 on 2022-09-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_builder_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builder',
            name='profileimg',
            field=models.ImageField(blank=True, null=True, upload_to='image/profile'),
        ),
    ]
